WITH CTE AS (
    SELECT
   TO_TIMESTAMP(STARTED_AT),
   DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
   HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
   DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME_STARTED_AT,
    CASE 
    when DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
    then 'WEEKEND'
    else 'BUSINESSDAY'
    END AS DAY_TYPE,
    MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT,

    CASE WHEN     MONTH(TO_TIMESTAMP(STARTED_AT)) in (  12,1,2)
    THEN 'WINTER'
    WHEN     MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
    THEN 'SPRING'
    WHEN     MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
    THEN 'SUMER'
    ELSE 'AUTUMN'
    END AS STATION_OF_YEAR
    FROM 
    {{ source('demo', 'bike') }}
  )

select * from CTE